package model;
// Generated 18/10/2019 10:39:39 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "Banco", schema = "dbo", catalog = "FIN")
public class Banco implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idBanco;
	private String numero;
	private String nome;
	private Set<Conta> contas = new HashSet<Conta>(0);

	public Banco() {
	}

	public Banco(String numero, String nome) {
		this.numero = numero;
		this.nome = nome;
	}

	public Banco(String numero, String nome, Set<Conta> contas) {
		this.numero = numero;
		this.nome = nome;
		this.contas = contas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idBanco", unique = true, nullable = false)
	public Integer getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(Integer idBanco) {
		this.idBanco = idBanco;
	}

	@Column(name = "numero", nullable = false)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
	public Set<Conta> getContas() {
		return this.contas;
	}

	public void setContas(Set<Conta> contas) {
		this.contas = contas;
	}

}
