package model;
// Generated 18/10/2019 10:39:39 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CentroCusto generated by hbm2java
 */
@Entity
@Table(name = "CentroCusto", schema = "dbo", catalog = "FIN", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class CentroCusto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCentroCusto;
	private CentroCusto centroCusto;
	private String nome;
	private String descricao;
	private Set<ReceitaMensal> receitaMensals = new HashSet<ReceitaMensal>(0);
	private Set<DespesaMensal> despesaMensals = new HashSet<DespesaMensal>(0);
	private Set<CentroCusto> centroCustos = new HashSet<CentroCusto>(0);
	private Set<ContaReceber> contaRecebers = new HashSet<ContaReceber>(0);
	private Set<ContaPagar> contaPagars = new HashSet<ContaPagar>(0);

	public CentroCusto() {
	}

	public CentroCusto(String nome) {
		this.nome = nome;
	}

	public CentroCusto(CentroCusto centroCusto, String nome, String descricao, Set<ReceitaMensal> receitaMensals,
			Set<DespesaMensal> despesaMensals, Set<CentroCusto> centroCustos, Set<ContaReceber> contaRecebers,
			Set<ContaPagar> contaPagars) {
		this.centroCusto = centroCusto;
		this.nome = nome;
		this.descricao = descricao;
		this.receitaMensals = receitaMensals;
		this.despesaMensals = despesaMensals;
		this.centroCustos = centroCustos;
		this.contaRecebers = contaRecebers;
		this.contaPagars = contaPagars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCentroCusto", unique = true, nullable = false)
	public Integer getIdCentroCusto() {
		return this.idCentroCusto;
	}

	public void setIdCentroCusto(Integer idCentroCusto) {
		this.idCentroCusto = idCentroCusto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCentroCustoPai")
	public CentroCusto getCentroCusto() {
		return this.centroCusto;
	}

	public void setCentroCusto(CentroCusto centroCusto) {
		this.centroCusto = centroCusto;
	}

	@Column(name = "nome", unique = true, nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroCusto")
	public Set<ReceitaMensal> getReceitaMensals() {
		return this.receitaMensals;
	}

	public void setReceitaMensals(Set<ReceitaMensal> receitaMensals) {
		this.receitaMensals = receitaMensals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroCusto")
	public Set<DespesaMensal> getDespesaMensals() {
		return this.despesaMensals;
	}

	public void setDespesaMensals(Set<DespesaMensal> despesaMensals) {
		this.despesaMensals = despesaMensals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroCusto")
	public Set<CentroCusto> getCentroCustos() {
		return this.centroCustos;
	}

	public void setCentroCustos(Set<CentroCusto> centroCustos) {
		this.centroCustos = centroCustos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroCusto")
	public Set<ContaReceber> getContaRecebers() {
		return this.contaRecebers;
	}

	public void setContaRecebers(Set<ContaReceber> contaRecebers) {
		this.contaRecebers = contaRecebers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroCusto")
	public Set<ContaPagar> getContaPagars() {
		return this.contaPagars;
	}

	public void setContaPagars(Set<ContaPagar> contaPagars) {
		this.contaPagars = contaPagars;
	}

	@Override
	public String toString() {
		return nome;
	}

	
}
