package model;
// Generated 15/05/2019 11:16:03 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name = "Cidade", schema = "dbo", catalog = "Fin3l")
public class Cidade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCidade;
	private Estado estado;
	private String nome;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<Empresa> empresas = new HashSet<Empresa>(0);
	private Set<Fornecedor> fornecedors = new HashSet<Fornecedor>(0);

	public Cidade() {
	}

	public Cidade(Estado estado, String nome) {
		this.estado = estado;
		this.nome = nome;
	}

	public Cidade(Estado estado, String nome, Set<Cliente> clientes, Set<Empresa> empresas,
			Set<Fornecedor> fornecedors) {
		this.estado = estado;
		this.nome = nome;
		this.clientes = clientes;
		this.empresas = empresas;
		this.fornecedors = fornecedors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCidade", unique = true, nullable = false)
	public Integer getIdCidade() {
		return this.idCidade;
	}

	public void setIdCidade(Integer idCidade) {
		this.idCidade = idCidade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uf", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	public Set<Empresa> getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set<Empresa> empresas) {
		this.empresas = empresas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	public Set<Fornecedor> getFornecedors() {
		return this.fornecedors;
	}

	public void setFornecedors(Set<Fornecedor> fornecedors) {
		this.fornecedors = fornecedors;
	}

	@Override
	public String toString() {
		return getNome();
	}

}
