package model;
// Generated 21/08/2019 02:04:11 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "Cliente", catalog = "FIN")
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3076530573712622177L;
	private int idCliente;
	private Cidade cidade;
	private String cpf;
	private String cnpj;
	private String rg;
	private String ie;
	private String nome;
	private String endereco;
	private String bairro;
	private String numero;
	private String complemento;
	private String cep;
	private String telefone;
	private String celular;
	private String email;
	private Date dataNascimento;
	private Set<ContaReceber> contaRecebers = new HashSet<ContaReceber>(0);
	private Set<ReceitaMensal> receitaMensals = new HashSet<ReceitaMensal>(0);

	public Cliente() {
	}

	public Cliente(int idCliente, String nome) {
		this.idCliente = idCliente;
		this.nome = nome;
	}

	public Cliente(int idCliente, Cidade cidade, String cpf, String cnpj, String rg, String ie, String nome,
			String endereco, String bairro, String numero, String complemento, String cep, String telefone,
			String celular, String email, Date dataNascimento, Set<ContaReceber> contaRecebers,
			Set<ReceitaMensal> receitaMensals) {
		this.idCliente = idCliente;
		this.cidade = cidade;
		this.cpf = cpf;
		this.cnpj = cnpj;
		this.rg = rg;
		this.ie = ie;
		this.nome = nome;
		this.endereco = endereco;
		this.bairro = bairro;
		this.numero = numero;
		this.complemento = complemento;
		this.cep = cep;
		this.telefone = telefone;
		this.celular = celular;
		this.email = email;
		this.dataNascimento = dataNascimento;
		this.contaRecebers = contaRecebers;
		this.receitaMensals = receitaMensals;
	}

	@Id

	@Column(name = "idCliente", unique = true, nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCidade")
	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	@Column(name = "cpf")
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "cnpj")
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "rg")
	public String getRg() {
		return this.rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	@Column(name = "ie")
	public String getIe() {
		return this.ie;
	}

	public void setIe(String ie) {
		this.ie = ie;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "endereco")
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "bairro")
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "numero")
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "complemento")
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "cep")
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "telefone")
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "celular")
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataNascimento", length = 10)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<ContaReceber> getContaRecebers() {
		return this.contaRecebers;
	}

	public void setContaRecebers(Set<ContaReceber> contaRecebers) {
		this.contaRecebers = contaRecebers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<ReceitaMensal> getReceitaMensals() {
		return this.receitaMensals;
	}

	public void setReceitaMensals(Set<ReceitaMensal> receitaMensals) {
		this.receitaMensals = receitaMensals;
	}

}
