package model;
// Generated 30/01/2020 13:44:51 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContaDataViewId generated by hbm2java
 */
@Embeddable
public class ContaDataViewId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idContaPagar;
	private Integer idContaReceber;
	private int idConta;
	private int idTransacao;
	private Date data;
	private String numeroDoc;
	private String historico;
	private String tipo;
	private BigDecimal credito;
	private BigDecimal debito;
	private BigDecimal saldo;
	private Date dataInsercao;
	private String fornecedorCp;
	private String centroCustoCp;
	private String planoContaCp;
	private BigDecimal valorPagamento;
	private Date dataInsercaoCp;
	private String clienteCr;
	private String centroCustoCr;
	private String planoContaCr;
	private BigDecimal valorRecebimento;
	private Date dataInsercaoCr;

	public ContaDataViewId() {
	}

	public ContaDataViewId(int idConta, int idTransacao, Date data, String tipo, BigDecimal saldo, Date dataInsercao,
			Date dataInsercaoCp, Date dataInsercaoCr) {
		this.idConta = idConta;
		this.idTransacao = idTransacao;
		this.data = data;
		this.tipo = tipo;
		this.saldo = saldo;
		this.dataInsercao = dataInsercao;
		this.dataInsercaoCp = dataInsercaoCp;
		this.dataInsercaoCr = dataInsercaoCr;
	}

	public ContaDataViewId(Integer idContaPagar, Integer idContaReceber, int idConta, int idTransacao, Date data,
			String numeroDoc, String historico, String tipo, BigDecimal credito, BigDecimal debito, BigDecimal saldo,
			Date dataInsercao, String fornecedorCp, String centroCustoCp, String planoContaCp,
			BigDecimal valorPagamento, Date dataInsercaoCp, String clienteCr, String centroCustoCr, String planoContaCr,
			BigDecimal valorRecebimento, Date dataInsercaoCr) {
		this.idContaPagar = idContaPagar;
		this.idContaReceber = idContaReceber;
		this.idConta = idConta;
		this.idTransacao = idTransacao;
		this.data = data;
		this.numeroDoc = numeroDoc;
		this.historico = historico;
		this.tipo = tipo;
		this.credito = credito;
		this.debito = debito;
		this.saldo = saldo;
		this.dataInsercao = dataInsercao;
		this.fornecedorCp = fornecedorCp;
		this.centroCustoCp = centroCustoCp;
		this.planoContaCp = planoContaCp;
		this.valorPagamento = valorPagamento;
		this.dataInsercaoCp = dataInsercaoCp;
		this.clienteCr = clienteCr;
		this.centroCustoCr = centroCustoCr;
		this.planoContaCr = planoContaCr;
		this.valorRecebimento = valorRecebimento;
		this.dataInsercaoCr = dataInsercaoCr;
	}

	@Column(name = "idContaPagar")
	public Integer getIdContaPagar() {
		return this.idContaPagar;
	}

	public void setIdContaPagar(Integer idContaPagar) {
		this.idContaPagar = idContaPagar;
	}

	@Column(name = "idContaReceber")
	public Integer getIdContaReceber() {
		return this.idContaReceber;
	}

	public void setIdContaReceber(Integer idContaReceber) {
		this.idContaReceber = idContaReceber;
	}

	@Column(name = "idConta", nullable = false)
	public int getIdConta() {
		return this.idConta;
	}

	public void setIdConta(int idConta) {
		this.idConta = idConta;
	}

	@Column(name = "idTransacao", nullable = false)
	public int getIdTransacao() {
		return this.idTransacao;
	}

	public void setIdTransacao(int idTransacao) {
		this.idTransacao = idTransacao;
	}

	@Column(name = "data", nullable = false, length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "numeroDoc")
	public String getNumeroDoc() {
		return this.numeroDoc;
	}

	public void setNumeroDoc(String numeroDoc) {
		this.numeroDoc = numeroDoc;
	}

	@Column(name = "historico")
	public String getHistorico() {
		return this.historico;
	}

	public void setHistorico(String historico) {
		this.historico = historico;
	}

	@Column(name = "tipo", nullable = false)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "credito")
	public BigDecimal getCredito() {
		return this.credito;
	}

	public void setCredito(BigDecimal credito) {
		this.credito = credito;
	}

	@Column(name = "debito")
	public BigDecimal getDebito() {
		return this.debito;
	}

	public void setDebito(BigDecimal debito) {
		this.debito = debito;
	}

	@Column(name = "saldo", nullable = false)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Column(name = "dataInsercao", nullable = false, length = 23)
	public Date getDataInsercao() {
		return this.dataInsercao;
	}

	public void setDataInsercao(Date dataInsercao) {
		this.dataInsercao = dataInsercao;
	}

	@Column(name = "fornecedorCP")
	public String getFornecedorCp() {
		return this.fornecedorCp;
	}

	public void setFornecedorCp(String fornecedorCp) {
		this.fornecedorCp = fornecedorCp;
	}

	@Column(name = "centroCustoCP")
	public String getCentroCustoCp() {
		return this.centroCustoCp;
	}

	public void setCentroCustoCp(String centroCustoCp) {
		this.centroCustoCp = centroCustoCp;
	}

	@Column(name = "planoContaCP")
	public String getPlanoContaCp() {
		return this.planoContaCp;
	}

	public void setPlanoContaCp(String planoContaCp) {
		this.planoContaCp = planoContaCp;
	}

	@Column(name = "valorPagamento")
	public BigDecimal getValorPagamento() {
		return this.valorPagamento;
	}

	public void setValorPagamento(BigDecimal valorPagamento) {
		this.valorPagamento = valorPagamento;
	}

	@Column(name = "dataInsercaoCP", nullable = false, length = 23)
	public Date getDataInsercaoCp() {
		return this.dataInsercaoCp;
	}

	public void setDataInsercaoCp(Date dataInsercaoCp) {
		this.dataInsercaoCp = dataInsercaoCp;
	}

	@Column(name = "clienteCR")
	public String getClienteCr() {
		return this.clienteCr;
	}

	public void setClienteCr(String clienteCr) {
		this.clienteCr = clienteCr;
	}

	@Column(name = "centroCustoCR")
	public String getCentroCustoCr() {
		return this.centroCustoCr;
	}

	public void setCentroCustoCr(String centroCustoCr) {
		this.centroCustoCr = centroCustoCr;
	}

	@Column(name = "planoContaCR")
	public String getPlanoContaCr() {
		return this.planoContaCr;
	}

	public void setPlanoContaCr(String planoContaCr) {
		this.planoContaCr = planoContaCr;
	}

	@Column(name = "valorRecebimento")
	public BigDecimal getValorRecebimento() {
		return this.valorRecebimento;
	}

	public void setValorRecebimento(BigDecimal valorRecebimento) {
		this.valorRecebimento = valorRecebimento;
	}

	@Column(name = "dataInsercaoCR", nullable = false, length = 23)
	public Date getDataInsercaoCr() {
		return this.dataInsercaoCr;
	}

	public void setDataInsercaoCr(Date dataInsercaoCr) {
		this.dataInsercaoCr = dataInsercaoCr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContaDataViewId))
			return false;
		ContaDataViewId castOther = (ContaDataViewId) other;

		return ((this.getIdContaPagar() == castOther.getIdContaPagar()) || (this.getIdContaPagar() != null
				&& castOther.getIdContaPagar() != null && this.getIdContaPagar().equals(castOther.getIdContaPagar())))
				&& ((this.getIdContaReceber() == castOther.getIdContaReceber())
						|| (this.getIdContaReceber() != null && castOther.getIdContaReceber() != null
								&& this.getIdContaReceber().equals(castOther.getIdContaReceber())))
				&& (this.getIdConta() == castOther.getIdConta())
				&& (this.getIdTransacao() == castOther.getIdTransacao())
				&& ((this.getData() == castOther.getData()) || (this.getData() != null && castOther.getData() != null
						&& this.getData().equals(castOther.getData())))
				&& ((this.getNumeroDoc() == castOther.getNumeroDoc()) || (this.getNumeroDoc() != null
						&& castOther.getNumeroDoc() != null && this.getNumeroDoc().equals(castOther.getNumeroDoc())))
				&& ((this.getHistorico() == castOther.getHistorico()) || (this.getHistorico() != null
						&& castOther.getHistorico() != null && this.getHistorico().equals(castOther.getHistorico())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
						&& this.getTipo().equals(castOther.getTipo())))
				&& ((this.getCredito() == castOther.getCredito()) || (this.getCredito() != null
						&& castOther.getCredito() != null && this.getCredito().equals(castOther.getCredito())))
				&& ((this.getDebito() == castOther.getDebito()) || (this.getDebito() != null
						&& castOther.getDebito() != null && this.getDebito().equals(castOther.getDebito())))
				&& ((this.getSaldo() == castOther.getSaldo()) || (this.getSaldo() != null
						&& castOther.getSaldo() != null && this.getSaldo().equals(castOther.getSaldo())))
				&& ((this.getDataInsercao() == castOther.getDataInsercao())
						|| (this.getDataInsercao() != null && castOther.getDataInsercao() != null
								&& this.getDataInsercao().equals(castOther.getDataInsercao())))
				&& ((this.getFornecedorCp() == castOther.getFornecedorCp())
						|| (this.getFornecedorCp() != null && castOther.getFornecedorCp() != null
								&& this.getFornecedorCp().equals(castOther.getFornecedorCp())))
				&& ((this.getCentroCustoCp() == castOther.getCentroCustoCp())
						|| (this.getCentroCustoCp() != null && castOther.getCentroCustoCp() != null
								&& this.getCentroCustoCp().equals(castOther.getCentroCustoCp())))
				&& ((this.getPlanoContaCp() == castOther.getPlanoContaCp())
						|| (this.getPlanoContaCp() != null && castOther.getPlanoContaCp() != null
								&& this.getPlanoContaCp().equals(castOther.getPlanoContaCp())))
				&& ((this.getValorPagamento() == castOther.getValorPagamento())
						|| (this.getValorPagamento() != null && castOther.getValorPagamento() != null
								&& this.getValorPagamento().equals(castOther.getValorPagamento())))
				&& ((this.getDataInsercaoCp() == castOther.getDataInsercaoCp())
						|| (this.getDataInsercaoCp() != null && castOther.getDataInsercaoCp() != null
								&& this.getDataInsercaoCp().equals(castOther.getDataInsercaoCp())))
				&& ((this.getClienteCr() == castOther.getClienteCr()) || (this.getClienteCr() != null
						&& castOther.getClienteCr() != null && this.getClienteCr().equals(castOther.getClienteCr())))
				&& ((this.getCentroCustoCr() == castOther.getCentroCustoCr())
						|| (this.getCentroCustoCr() != null && castOther.getCentroCustoCr() != null
								&& this.getCentroCustoCr().equals(castOther.getCentroCustoCr())))
				&& ((this.getPlanoContaCr() == castOther.getPlanoContaCr())
						|| (this.getPlanoContaCr() != null && castOther.getPlanoContaCr() != null
								&& this.getPlanoContaCr().equals(castOther.getPlanoContaCr())))
				&& ((this.getValorRecebimento() == castOther.getValorRecebimento())
						|| (this.getValorRecebimento() != null && castOther.getValorRecebimento() != null
								&& this.getValorRecebimento().equals(castOther.getValorRecebimento())))
				&& ((this.getDataInsercaoCr() == castOther.getDataInsercaoCr())
						|| (this.getDataInsercaoCr() != null && castOther.getDataInsercaoCr() != null
								&& this.getDataInsercaoCr().equals(castOther.getDataInsercaoCr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdContaPagar() == null ? 0 : this.getIdContaPagar().hashCode());
		result = 37 * result + (getIdContaReceber() == null ? 0 : this.getIdContaReceber().hashCode());
		result = 37 * result + this.getIdConta();
		result = 37 * result + this.getIdTransacao();
		result = 37 * result + (getData() == null ? 0 : this.getData().hashCode());
		result = 37 * result + (getNumeroDoc() == null ? 0 : this.getNumeroDoc().hashCode());
		result = 37 * result + (getHistorico() == null ? 0 : this.getHistorico().hashCode());
		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result + (getCredito() == null ? 0 : this.getCredito().hashCode());
		result = 37 * result + (getDebito() == null ? 0 : this.getDebito().hashCode());
		result = 37 * result + (getSaldo() == null ? 0 : this.getSaldo().hashCode());
		result = 37 * result + (getDataInsercao() == null ? 0 : this.getDataInsercao().hashCode());
		result = 37 * result + (getFornecedorCp() == null ? 0 : this.getFornecedorCp().hashCode());
		result = 37 * result + (getCentroCustoCp() == null ? 0 : this.getCentroCustoCp().hashCode());
		result = 37 * result + (getPlanoContaCp() == null ? 0 : this.getPlanoContaCp().hashCode());
		result = 37 * result + (getValorPagamento() == null ? 0 : this.getValorPagamento().hashCode());
		result = 37 * result + (getDataInsercaoCp() == null ? 0 : this.getDataInsercaoCp().hashCode());
		result = 37 * result + (getClienteCr() == null ? 0 : this.getClienteCr().hashCode());
		result = 37 * result + (getCentroCustoCr() == null ? 0 : this.getCentroCustoCr().hashCode());
		result = 37 * result + (getPlanoContaCr() == null ? 0 : this.getPlanoContaCr().hashCode());
		result = 37 * result + (getValorRecebimento() == null ? 0 : this.getValorRecebimento().hashCode());
		result = 37 * result + (getDataInsercaoCr() == null ? 0 : this.getDataInsercaoCr().hashCode());
		return result;
	}

}
