package model;
// Generated 30/01/2020 13:44:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContaReceberDataView generated by hbm2java
 */
@Entity
@Table(name = "ContaReceberDataView", schema = "dbo", catalog = "FIN")
public class ContaReceberDataView implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idContaReceber;
	private Date dataVenda;
	private String numero;
	private String documento;
	private String descricao;
	private BigDecimal valor;
	private Date dataVencimento;
	private Date dataRecebimento;
	private String observacao;
	private BigDecimal valorRecebimento;
	private String numeroBanco;
	private String numeroAgencia;
	private String numeroConta;
	private String numeroDocRecto;
	private String status;
	private Date dataInsercao;
	private Integer idCliente;
	private String clienteNome;
	private Integer idCentroCusto;
	private String centroCustoNome;
	private Integer idPlanoConta;
	private String planoContaNome;
	private Integer idFormaPagamento;
	private String codigo;

	public ContaReceberDataView() {
	}

	public ContaReceberDataView(int idContaReceber, Date dataVenda, BigDecimal valor, Date dataVencimento,
			String status, Date dataInsercao) {
		this.idContaReceber = idContaReceber;
		this.dataVenda = dataVenda;
		this.valor = valor;
		this.dataVencimento = dataVencimento;
		this.status = status;
		this.dataInsercao = dataInsercao;
	}

	public ContaReceberDataView(int idContaReceber, Date dataVenda, String numero, String documento, String descricao,
			BigDecimal valor, Date dataVencimento, Date dataRecebimento, String observacao, BigDecimal valorRecebimento,
			String numeroBanco, String numeroAgencia, String numeroConta, String numeroDocRecto, String status,
			Date dataInsercao, Integer idCliente, String clienteNome, Integer idCentroCusto, String centroCustoNome,
			Integer idPlanoConta, String planoContaNome, Integer idFormaPagamento, String codigo) {
		this.idContaReceber = idContaReceber;
		this.dataVenda = dataVenda;
		this.numero = numero;
		this.documento = documento;
		this.descricao = descricao;
		this.valor = valor;
		this.dataVencimento = dataVencimento;
		this.dataRecebimento = dataRecebimento;
		this.observacao = observacao;
		this.valorRecebimento = valorRecebimento;
		this.numeroBanco = numeroBanco;
		this.numeroAgencia = numeroAgencia;
		this.numeroConta = numeroConta;
		this.numeroDocRecto = numeroDocRecto;
		this.status = status;
		this.dataInsercao = dataInsercao;
		this.idCliente = idCliente;
		this.clienteNome = clienteNome;
		this.idCentroCusto = idCentroCusto;
		this.centroCustoNome = centroCustoNome;
		this.idPlanoConta = idPlanoConta;
		this.planoContaNome = planoContaNome;
		this.idFormaPagamento = idFormaPagamento;
		this.codigo = codigo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idContaReceber", nullable = false)
	public int getIdContaReceber() {
		return this.idContaReceber;
	}

	public void setIdContaReceber(int idContaReceber) {
		this.idContaReceber = idContaReceber;
	}

	@Column(name = "dataVenda", nullable = false, length = 10)
	public Date getDataVenda() {
		return this.dataVenda;
	}

	public void setDataVenda(Date dataVenda) {
		this.dataVenda = dataVenda;
	}

	@Column(name = "numero")
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "documento")
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", nullable = false)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "dataVencimento", nullable = false, length = 10)
	public Date getDataVencimento() {
		return this.dataVencimento;
	}

	public void setDataVencimento(Date dataVencimento) {
		this.dataVencimento = dataVencimento;
	}

	@Column(name = "dataRecebimento", length = 10)
	public Date getDataRecebimento() {
		return this.dataRecebimento;
	}

	public void setDataRecebimento(Date dataRecebimento) {
		this.dataRecebimento = dataRecebimento;
	}

	@Column(name = "observacao")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "valorRecebimento")
	public BigDecimal getValorRecebimento() {
		return this.valorRecebimento;
	}

	public void setValorRecebimento(BigDecimal valorRecebimento) {
		this.valorRecebimento = valorRecebimento;
	}

	@Column(name = "numeroBanco")
	public String getNumeroBanco() {
		return this.numeroBanco;
	}

	public void setNumeroBanco(String numeroBanco) {
		this.numeroBanco = numeroBanco;
	}

	@Column(name = "numeroAgencia")
	public String getNumeroAgencia() {
		return this.numeroAgencia;
	}

	public void setNumeroAgencia(String numeroAgencia) {
		this.numeroAgencia = numeroAgencia;
	}

	@Column(name = "numeroConta")
	public String getNumeroConta() {
		return this.numeroConta;
	}

	public void setNumeroConta(String numeroConta) {
		this.numeroConta = numeroConta;
	}

	@Column(name = "numeroDocRecto")
	public String getNumeroDocRecto() {
		return this.numeroDocRecto;
	}

	public void setNumeroDocRecto(String numeroDocRecto) {
		this.numeroDocRecto = numeroDocRecto;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "dataInsercao", nullable = false, length = 23)
	public Date getDataInsercao() {
		return this.dataInsercao;
	}

	public void setDataInsercao(Date dataInsercao) {
		this.dataInsercao = dataInsercao;
	}

	@Column(name = "idCliente")
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "clienteNome")
	public String getClienteNome() {
		return this.clienteNome;
	}

	public void setClienteNome(String clienteNome) {
		this.clienteNome = clienteNome;
	}

	@Column(name = "idCentroCusto")
	public Integer getIdCentroCusto() {
		return this.idCentroCusto;
	}

	public void setIdCentroCusto(Integer idCentroCusto) {
		this.idCentroCusto = idCentroCusto;
	}

	@Column(name = "centroCustoNome")
	public String getCentroCustoNome() {
		return this.centroCustoNome;
	}

	public void setCentroCustoNome(String centroCustoNome) {
		this.centroCustoNome = centroCustoNome;
	}

	@Column(name = "idPlanoConta")
	public Integer getIdPlanoConta() {
		return this.idPlanoConta;
	}

	public void setIdPlanoConta(Integer idPlanoConta) {
		this.idPlanoConta = idPlanoConta;
	}

	@Column(name = "planoContaNome")
	public String getPlanoContaNome() {
		return this.planoContaNome;
	}

	public void setPlanoContaNome(String planoContaNome) {
		this.planoContaNome = planoContaNome;
	}

	@Column(name = "idFormaPagamento")
	public Integer getIdFormaPagamento() {
		return this.idFormaPagamento;
	}

	public void setIdFormaPagamento(Integer idFormaPagamento) {
		this.idFormaPagamento = idFormaPagamento;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}
}
