package model;
// Generated 21/08/2019 02:04:11 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContaPagar generated by hbm2java
 */
@Entity
@Table(name = "ContaPagar", catalog = "FIN")
public class ContaPagar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5428703496812774900L;
	private int idContaPagar;
	private CentroCusto centroCusto;
	private FormaPagamento formaPagamento;
	private Fornecedor fornecedor;
	private PlanoConta planoConta;
	private Transacao transacao;
	private Date dataCompra;
	private String numero;
	private String documento;
	private String descricao;
	private BigDecimal valor;
	private Date dataVencimento;
	private Date dataPagamento;
	private String observacao;
	private BigDecimal valorPagamento;
	private Serializable numeroBanco;
	private String numeroAgencia;
	private String numeroConta;
	private String numeroDocPagto;
	private Serializable status;
	private Date dataInsercao;
	private String tag;

	public ContaPagar() {
	}

	public ContaPagar(int idContaPagar, Date dataCompra, BigDecimal valor, Date dataVencimento, Serializable status,
			Date dataInsercao) {
		this.idContaPagar = idContaPagar;
		this.dataCompra = dataCompra;
		this.valor = valor;
		this.dataVencimento = dataVencimento;
		this.status = status;
		this.dataInsercao = dataInsercao;
	}

	public ContaPagar(int idContaPagar, CentroCusto centroCusto, FormaPagamento formaPagamento, Fornecedor fornecedor,
			PlanoConta planoConta, Transacao transacao, Date dataCompra, String numero, String documento,
			String descricao, BigDecimal valor, Date dataVencimento, Date dataPagamento, String observacao,
			BigDecimal valorPagamento, Serializable numeroBanco, String numeroAgencia, String numeroConta,
			String numeroDocPagto, Serializable status, Date dataInsercao, String tag) {
		this.idContaPagar = idContaPagar;
		this.centroCusto = centroCusto;
		this.formaPagamento = formaPagamento;
		this.fornecedor = fornecedor;
		this.planoConta = planoConta;
		this.transacao = transacao;
		this.dataCompra = dataCompra;
		this.numero = numero;
		this.documento = documento;
		this.descricao = descricao;
		this.valor = valor;
		this.dataVencimento = dataVencimento;
		this.dataPagamento = dataPagamento;
		this.observacao = observacao;
		this.valorPagamento = valorPagamento;
		this.numeroBanco = numeroBanco;
		this.numeroAgencia = numeroAgencia;
		this.numeroConta = numeroConta;
		this.numeroDocPagto = numeroDocPagto;
		this.status = status;
		this.dataInsercao = dataInsercao;
		this.tag = tag;
	}

	@Id

	@Column(name = "idContaPagar", unique = true, nullable = false)
	public int getIdContaPagar() {
		return this.idContaPagar;
	}

	public void setIdContaPagar(int idContaPagar) {
		this.idContaPagar = idContaPagar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCentroCusto")
	public CentroCusto getCentroCusto() {
		return this.centroCusto;
	}

	public void setCentroCusto(CentroCusto centroCusto) {
		this.centroCusto = centroCusto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFormaPagamento")
	public FormaPagamento getFormaPagamento() {
		return this.formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFornecedor")
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPlanoConta")
	public PlanoConta getPlanoConta() {
		return this.planoConta;
	}

	public void setPlanoConta(PlanoConta planoConta) {
		this.planoConta = planoConta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTransacao")
	public Transacao getTransacao() {
		return this.transacao;
	}

	public void setTransacao(Transacao transacao) {
		this.transacao = transacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataCompra", nullable = false, length = 10)
	public Date getDataCompra() {
		return this.dataCompra;
	}

	public void setDataCompra(Date dataCompra) {
		this.dataCompra = dataCompra;
	}

	@Column(name = "numero")
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "documento")
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "valor", nullable = false)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataVencimento", nullable = false, length = 10)
	public Date getDataVencimento() {
		return this.dataVencimento;
	}

	public void setDataVencimento(Date dataVencimento) {
		this.dataVencimento = dataVencimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataPagamento", length = 10)
	public Date getDataPagamento() {
		return this.dataPagamento;
	}

	public void setDataPagamento(Date dataPagamento) {
		this.dataPagamento = dataPagamento;
	}

	@Column(name = "observacao")
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "valorPagamento")
	public BigDecimal getValorPagamento() {
		return this.valorPagamento;
	}

	public void setValorPagamento(BigDecimal valorPagamento) {
		this.valorPagamento = valorPagamento;
	}

	@Column(name = "numeroBanco")
	public Serializable getNumeroBanco() {
		return this.numeroBanco;
	}

	public void setNumeroBanco(Serializable numeroBanco) {
		this.numeroBanco = numeroBanco;
	}

	@Column(name = "numeroAgencia")
	public String getNumeroAgencia() {
		return this.numeroAgencia;
	}

	public void setNumeroAgencia(String numeroAgencia) {
		this.numeroAgencia = numeroAgencia;
	}

	@Column(name = "numeroConta")
	public String getNumeroConta() {
		return this.numeroConta;
	}

	public void setNumeroConta(String numeroConta) {
		this.numeroConta = numeroConta;
	}

	@Column(name = "numeroDocPagto")
	public String getNumeroDocPagto() {
		return this.numeroDocPagto;
	}

	public void setNumeroDocPagto(String numeroDocPagto) {
		this.numeroDocPagto = numeroDocPagto;
	}

	@Column(name = "status", nullable = false)
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataInsercao", nullable = false, length = 23)
	public Date getDataInsercao() {
		return this.dataInsercao;
	}

	public void setDataInsercao(Date dataInsercao) {
		this.dataInsercao = dataInsercao;
	}

	@Column(name = "tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

}
