package model;
// Generated 30/01/2020 13:44:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContaDataView generated by hbm2java
 */
@Entity
@Table(name = "ContaDataView", schema = "dbo", catalog = "FIN")
public class ContaDataView implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ContaDataViewId id;

	public ContaDataView() {
	}

	public ContaDataView(ContaDataViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idContaPagar", column = @Column(name = "idContaPagar")),
			@AttributeOverride(name = "idContaReceber", column = @Column(name = "idContaReceber")),
			@AttributeOverride(name = "idConta", column = @Column(name = "idConta", nullable = false)),
			@AttributeOverride(name = "idTransacao", column = @Column(name = "idTransacao", nullable = false)),
			@AttributeOverride(name = "data", column = @Column(name = "data", nullable = false, length = 10)),
			@AttributeOverride(name = "numeroDoc", column = @Column(name = "numeroDoc")),
			@AttributeOverride(name = "historico", column = @Column(name = "historico")),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo", nullable = false)),
			@AttributeOverride(name = "credito", column = @Column(name = "credito")),
			@AttributeOverride(name = "debito", column = @Column(name = "debito")),
			@AttributeOverride(name = "saldo", column = @Column(name = "saldo", nullable = false)),
			@AttributeOverride(name = "dataInsercao", column = @Column(name = "dataInsercao", nullable = false, length = 23)),
			@AttributeOverride(name = "fornecedorCp", column = @Column(name = "fornecedorCP")),
			@AttributeOverride(name = "centroCustoCp", column = @Column(name = "centroCustoCP")),
			@AttributeOverride(name = "planoContaCp", column = @Column(name = "planoContaCP")),
			@AttributeOverride(name = "valorPagamento", column = @Column(name = "valorPagamento")),
			@AttributeOverride(name = "dataInsercaoCp", column = @Column(name = "dataInsercaoCP", nullable = false, length = 23)),
			@AttributeOverride(name = "clienteCr", column = @Column(name = "clienteCR")),
			@AttributeOverride(name = "centroCustoCr", column = @Column(name = "centroCustoCR")),
			@AttributeOverride(name = "planoContaCr", column = @Column(name = "planoContaCR")),
			@AttributeOverride(name = "valorRecebimento", column = @Column(name = "valorRecebimento")),
			@AttributeOverride(name = "dataInsercaoCr", column = @Column(name = "dataInsercaoCR", nullable = false, length = 23)) })
	public ContaDataViewId getId() {
		return this.id;
	}

	public void setId(ContaDataViewId id) {
		this.id = id;
	}

}
