package model;
// Generated 21/08/2019 02:04:11 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DespesaMensal generated by hbm2java
 */
@Entity
@Table(name = "DespesaMensal", catalog = "FIN")
public class DespesaMensal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3178695470961312484L;
	private int idDespesaMensal;
	private CentroCusto centroCusto;
	private FormaPagamento formaPagamento;
	private Fornecedor fornecedor;
	private PlanoConta planoConta;
	private int diaVencimento;
	private BigDecimal valor;

	public DespesaMensal() {
	}

	public DespesaMensal(int idDespesaMensal, int diaVencimento, BigDecimal valor) {
		this.idDespesaMensal = idDespesaMensal;
		this.diaVencimento = diaVencimento;
		this.valor = valor;
	}

	public DespesaMensal(int idDespesaMensal, CentroCusto centroCusto, FormaPagamento formaPagamento,
			Fornecedor fornecedor, PlanoConta planoConta, int diaVencimento, BigDecimal valor) {
		this.idDespesaMensal = idDespesaMensal;
		this.centroCusto = centroCusto;
		this.formaPagamento = formaPagamento;
		this.fornecedor = fornecedor;
		this.planoConta = planoConta;
		this.diaVencimento = diaVencimento;
		this.valor = valor;
	}

	@Id

	@Column(name = "idDespesaMensal", unique = true, nullable = false)
	public int getIdDespesaMensal() {
		return this.idDespesaMensal;
	}

	public void setIdDespesaMensal(int idDespesaMensal) {
		this.idDespesaMensal = idDespesaMensal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCentroCusto")
	public CentroCusto getCentroCusto() {
		return this.centroCusto;
	}

	public void setCentroCusto(CentroCusto centroCusto) {
		this.centroCusto = centroCusto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFormaPagamento")
	public FormaPagamento getFormaPagamento() {
		return this.formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFornecedor")
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPlanoConta")
	public PlanoConta getPlanoConta() {
		return this.planoConta;
	}

	public void setPlanoConta(PlanoConta planoConta) {
		this.planoConta = planoConta;
	}

	@Column(name = "diaVencimento", nullable = false)
	public int getDiaVencimento() {
		return this.diaVencimento;
	}

	public void setDiaVencimento(int diaVencimento) {
		this.diaVencimento = diaVencimento;
	}

	@Column(name = "valor", nullable = false)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
