package model;
// Generated 21/08/2019 02:04:11 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPagamento generated by hbm2java
 */
@Entity
@Table(name = "FormaPagamento", catalog = "FIN")
public class FormaPagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2773508219612883665L;
	private int idFormaPagamento;
	private Serializable codigo;
	private String nome;
	private String descricao;
	private Set<DespesaMensal> despesaMensals = new HashSet<DespesaMensal>(0);
	private Set<ContaReceber> contaRecebers = new HashSet<ContaReceber>(0);
	private Set<ContaPagar> contaPagars = new HashSet<ContaPagar>(0);
	private Set<ReceitaMensal> receitaMensals = new HashSet<ReceitaMensal>(0);

	public FormaPagamento() {
	}

	public FormaPagamento(int idFormaPagamento, Serializable codigo, String nome) {
		this.idFormaPagamento = idFormaPagamento;
		this.codigo = codigo;
		this.nome = nome;
	}

	public FormaPagamento(int idFormaPagamento, Serializable codigo, String nome, String descricao,
			Set<DespesaMensal> despesaMensals, Set<ContaReceber> contaRecebers, Set<ContaPagar> contaPagars,
			Set<ReceitaMensal> receitaMensals) {
		this.idFormaPagamento = idFormaPagamento;
		this.codigo = codigo;
		this.nome = nome;
		this.descricao = descricao;
		this.despesaMensals = despesaMensals;
		this.contaRecebers = contaRecebers;
		this.contaPagars = contaPagars;
		this.receitaMensals = receitaMensals;
	}

	@Id

	@Column(name = "idFormaPagamento", unique = true, nullable = false)
	public int getIdFormaPagamento() {
		return this.idFormaPagamento;
	}

	public void setIdFormaPagamento(int idFormaPagamento) {
		this.idFormaPagamento = idFormaPagamento;
	}

	@Column(name = "codigo", nullable = false)
	public Serializable getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Serializable codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formaPagamento")
	public Set<DespesaMensal> getDespesaMensals() {
		return this.despesaMensals;
	}

	public void setDespesaMensals(Set<DespesaMensal> despesaMensals) {
		this.despesaMensals = despesaMensals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formaPagamento")
	public Set<ContaReceber> getContaRecebers() {
		return this.contaRecebers;
	}

	public void setContaRecebers(Set<ContaReceber> contaRecebers) {
		this.contaRecebers = contaRecebers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formaPagamento")
	public Set<ContaPagar> getContaPagars() {
		return this.contaPagars;
	}

	public void setContaPagars(Set<ContaPagar> contaPagars) {
		this.contaPagars = contaPagars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formaPagamento")
	public Set<ReceitaMensal> getReceitaMensals() {
		return this.receitaMensals;
	}

	public void setReceitaMensals(Set<ReceitaMensal> receitaMensals) {
		this.receitaMensals = receitaMensals;
	}

}
