package model;
// Generated 21/08/2019 02:04:11 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "Marca", catalog = "FIN")
public class Marca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8757145416906216446L;
	private int idMarca;
	private String nome;
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Marca() {
	}

	public Marca(int idMarca, String nome) {
		this.idMarca = idMarca;
		this.nome = nome;
	}

	public Marca(int idMarca, String nome, Set<Produto> produtos) {
		this.idMarca = idMarca;
		this.nome = nome;
		this.produtos = produtos;
	}

	@Id

	@Column(name = "idMarca", unique = true, nullable = false)
	public int getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(int idMarca) {
		this.idMarca = idMarca;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
