package model;
// Generated 18/10/2019 10:39:39 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "Perfil", schema = "dbo", catalog = "FIN")
public class Perfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPerfil;
	private String nome;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Permissao> permissaos = new HashSet<Permissao>(0);

	public Perfil() {
	}

	public Perfil(String nome) {
		this.nome = nome;
	}

	public Perfil(String nome, Set<Usuario> usuarios, Set<Permissao> permissaos) {
		this.nome = nome;
		this.usuarios = usuarios;
		this.permissaos = permissaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPerfil", unique = true, nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "PerfilPermissao", schema = "dbo", catalog = "FIN", joinColumns = {
			@JoinColumn(name = "idPerfil", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idPermissao", nullable = false, updatable = false) })
	public Set<Permissao> getPermissaos() {
		return this.permissaos;
	}

	public void setPermissaos(Set<Permissao> permissaos) {
		this.permissaos = permissaos;
	}

}
