package model;
// Generated 21/08/2019 02:04:11 by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "Produto", catalog = "FIN")
public class Produto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4332288034865701320L;
	private int idProduto;
	private Categoria categoria;
	private Fornecedor fornecedor;
	private Marca marca;
	private Serializable codigo;
	private String nome;
	private String descricao;
	private BigDecimal precoCusto;
	private BigDecimal precoVenda;

	public Produto() {
	}

	public Produto(int idProduto) {
		this.idProduto = idProduto;
	}

	public Produto(int idProduto, Categoria categoria, Fornecedor fornecedor, Marca marca, Serializable codigo,
			String nome, String descricao, BigDecimal precoCusto, BigDecimal precoVenda) {
		this.idProduto = idProduto;
		this.categoria = categoria;
		this.fornecedor = fornecedor;
		this.marca = marca;
		this.codigo = codigo;
		this.nome = nome;
		this.descricao = descricao;
		this.precoCusto = precoCusto;
		this.precoVenda = precoVenda;
	}

	@Id

	@Column(name = "idProduto", unique = true, nullable = false)
	public int getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(int idProduto) {
		this.idProduto = idProduto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCategoria")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFornecedor")
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMarca")
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "codigo")
	public Serializable getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Serializable codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "precoCusto")
	public BigDecimal getPrecoCusto() {
		return this.precoCusto;
	}

	public void setPrecoCusto(BigDecimal precoCusto) {
		this.precoCusto = precoCusto;
	}

	@Column(name = "precoVenda")
	public BigDecimal getPrecoVenda() {
		return this.precoVenda;
	}

	public void setPrecoVenda(BigDecimal precoVenda) {
		this.precoVenda = precoVenda;
	}

}
