package model;
// Generated 18/10/2019 10:39:39 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoConta generated by hbm2java
 */
@Entity
@Table(name = "TipoConta", schema = "dbo", catalog = "FIN")
public class TipoConta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTipoConta;
	private String nome;
	private Set<Conta> contas = new HashSet<Conta>(0);

	public TipoConta() {
	}

	public TipoConta(String nome) {
		this.nome = nome;
	}

	public TipoConta(String nome, Set<Conta> contas) {
		this.nome = nome;
		this.contas = contas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoConta", unique = true, nullable = false)
	public Integer getIdTipoConta() {
		return this.idTipoConta;
	}

	public void setIdTipoConta(Integer idTipoConta) {
		this.idTipoConta = idTipoConta;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoConta")
	public Set<Conta> getContas() {
		return this.contas;
	}

	public void setContas(Set<Conta> contas) {
		this.contas = contas;
	}

}
