package model;
// Generated 21/08/2019 02:04:11 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoConta generated by hbm2java
 */
@Entity
@Table(name = "TipoConta", catalog = "FIN")
public class TipoConta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4861090969851771240L;
	private int idTipoConta;
	private String nome;
	private Set<Conta> contas = new HashSet<Conta>(0);

	public TipoConta() {
	}

	public TipoConta(int idTipoConta, String nome) {
		this.idTipoConta = idTipoConta;
		this.nome = nome;
	}

	public TipoConta(int idTipoConta, String nome, Set<Conta> contas) {
		this.idTipoConta = idTipoConta;
		this.nome = nome;
		this.contas = contas;
	}

	@Id

	@Column(name = "idTipoConta", unique = true, nullable = false)
	public int getIdTipoConta() {
		return this.idTipoConta;
	}

	public void setIdTipoConta(int idTipoConta) {
		this.idTipoConta = idTipoConta;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoConta")
	public Set<Conta> getContas() {
		return this.contas;
	}

	public void setContas(Set<Conta> contas) {
		this.contas = contas;
	}

}
