package model;
// Generated 29/01/2020 15:19:00 by Hibernate Tools 5.4.7.Final

/**
 * TransacaoDataView generated by hbm2java
 */
public class TransacaoDataView implements java.io.Serializable {

	private TransacaoDataViewId id;

	public TransacaoDataView() {
	}

	public TransacaoDataView(TransacaoDataViewId id) {
		this.id = id;
	}

	public TransacaoDataViewId getId() {
		return this.id;
	}

	public void setId(TransacaoDataViewId id) {
		this.id = id;
	}

}
