package model;
// Generated 29/01/2020 15:19:00 by Hibernate Tools 5.4.7.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TransacaoDataViewId generated by hbm2java
 */
public class TransacaoDataViewId implements java.io.Serializable {

	private int id;
	private Date data;
	private Serializable numero;
	private BigDecimal valor;
	private String tipo;
	private Date vencimento;
	private Date dataBaixa;
	private BigDecimal valorBaixa;
	private Serializable status;
	private Integer idPessoa;
	private Serializable pessoaNome;
	private Integer idCentroCusto;
	private Serializable centroCustoNome;
	private Integer idPlanoConta;
	private Serializable planoContaNome;
	private Integer idFormaPagamento;
	private Serializable codigo;
	private Integer idTransacao;

	public TransacaoDataViewId() {
	}

	public TransacaoDataViewId(int id, Date data, BigDecimal valor, String tipo, Date vencimento, Serializable status) {
		this.id = id;
		this.data = data;
		this.valor = valor;
		this.tipo = tipo;
		this.vencimento = vencimento;
		this.status = status;
	}

	public TransacaoDataViewId(int id, Date data, Serializable numero, BigDecimal valor, String tipo, Date vencimento,
			Date dataBaixa, BigDecimal valorBaixa, Serializable status, Integer idPessoa, Serializable pessoaNome,
			Integer idCentroCusto, Serializable centroCustoNome, Integer idPlanoConta, Serializable planoContaNome,
			Integer idFormaPagamento, Serializable codigo, Integer idTransacao) {
		this.id = id;
		this.data = data;
		this.numero = numero;
		this.valor = valor;
		this.tipo = tipo;
		this.vencimento = vencimento;
		this.dataBaixa = dataBaixa;
		this.valorBaixa = valorBaixa;
		this.status = status;
		this.idPessoa = idPessoa;
		this.pessoaNome = pessoaNome;
		this.idCentroCusto = idCentroCusto;
		this.centroCustoNome = centroCustoNome;
		this.idPlanoConta = idPlanoConta;
		this.planoContaNome = planoContaNome;
		this.idFormaPagamento = idFormaPagamento;
		this.codigo = codigo;
		this.idTransacao = idTransacao;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Serializable getNumero() {
		return this.numero;
	}

	public void setNumero(Serializable numero) {
		this.numero = numero;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Date getVencimento() {
		return this.vencimento;
	}

	public void setVencimento(Date vencimento) {
		this.vencimento = vencimento;
	}

	public Date getDataBaixa() {
		return this.dataBaixa;
	}

	public void setDataBaixa(Date dataBaixa) {
		this.dataBaixa = dataBaixa;
	}

	public BigDecimal getValorBaixa() {
		return this.valorBaixa;
	}

	public void setValorBaixa(BigDecimal valorBaixa) {
		this.valorBaixa = valorBaixa;
	}

	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	public Integer getIdPessoa() {
		return this.idPessoa;
	}

	public void setIdPessoa(Integer idPessoa) {
		this.idPessoa = idPessoa;
	}

	public Serializable getPessoaNome() {
		return this.pessoaNome;
	}

	public void setPessoaNome(Serializable pessoaNome) {
		this.pessoaNome = pessoaNome;
	}

	public Integer getIdCentroCusto() {
		return this.idCentroCusto;
	}

	public void setIdCentroCusto(Integer idCentroCusto) {
		this.idCentroCusto = idCentroCusto;
	}

	public Serializable getCentroCustoNome() {
		return this.centroCustoNome;
	}

	public void setCentroCustoNome(Serializable centroCustoNome) {
		this.centroCustoNome = centroCustoNome;
	}

	public Integer getIdPlanoConta() {
		return this.idPlanoConta;
	}

	public void setIdPlanoConta(Integer idPlanoConta) {
		this.idPlanoConta = idPlanoConta;
	}

	public Serializable getPlanoContaNome() {
		return this.planoContaNome;
	}

	public void setPlanoContaNome(Serializable planoContaNome) {
		this.planoContaNome = planoContaNome;
	}

	public Integer getIdFormaPagamento() {
		return this.idFormaPagamento;
	}

	public void setIdFormaPagamento(Integer idFormaPagamento) {
		this.idFormaPagamento = idFormaPagamento;
	}

	public Serializable getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Serializable codigo) {
		this.codigo = codigo;
	}

	public Integer getIdTransacao() {
		return this.idTransacao;
	}

	public void setIdTransacao(Integer idTransacao) {
		this.idTransacao = idTransacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransacaoDataViewId))
			return false;
		TransacaoDataViewId castOther = (TransacaoDataViewId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getData() == castOther.getData()) || (this.getData() != null && castOther.getData() != null
						&& this.getData().equals(castOther.getData())))
				&& ((this.getNumero() == castOther.getNumero()) || (this.getNumero() != null
						&& castOther.getNumero() != null && this.getNumero().equals(castOther.getNumero())))
				&& ((this.getValor() == castOther.getValor()) || (this.getValor() != null
						&& castOther.getValor() != null && this.getValor().equals(castOther.getValor())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
						&& this.getTipo().equals(castOther.getTipo())))
				&& ((this.getVencimento() == castOther.getVencimento()) || (this.getVencimento() != null
						&& castOther.getVencimento() != null && this.getVencimento().equals(castOther.getVencimento())))
				&& ((this.getDataBaixa() == castOther.getDataBaixa()) || (this.getDataBaixa() != null
						&& castOther.getDataBaixa() != null && this.getDataBaixa().equals(castOther.getDataBaixa())))
				&& ((this.getValorBaixa() == castOther.getValorBaixa()) || (this.getValorBaixa() != null
						&& castOther.getValorBaixa() != null && this.getValorBaixa().equals(castOther.getValorBaixa())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getIdPessoa() == castOther.getIdPessoa()) || (this.getIdPessoa() != null
						&& castOther.getIdPessoa() != null && this.getIdPessoa().equals(castOther.getIdPessoa())))
				&& ((this.getPessoaNome() == castOther.getPessoaNome()) || (this.getPessoaNome() != null
						&& castOther.getPessoaNome() != null && this.getPessoaNome().equals(castOther.getPessoaNome())))
				&& ((this.getIdCentroCusto() == castOther.getIdCentroCusto())
						|| (this.getIdCentroCusto() != null && castOther.getIdCentroCusto() != null
								&& this.getIdCentroCusto().equals(castOther.getIdCentroCusto())))
				&& ((this.getCentroCustoNome() == castOther.getCentroCustoNome())
						|| (this.getCentroCustoNome() != null && castOther.getCentroCustoNome() != null
								&& this.getCentroCustoNome().equals(castOther.getCentroCustoNome())))
				&& ((this.getIdPlanoConta() == castOther.getIdPlanoConta())
						|| (this.getIdPlanoConta() != null && castOther.getIdPlanoConta() != null
								&& this.getIdPlanoConta().equals(castOther.getIdPlanoConta())))
				&& ((this.getPlanoContaNome() == castOther.getPlanoContaNome())
						|| (this.getPlanoContaNome() != null && castOther.getPlanoContaNome() != null
								&& this.getPlanoContaNome().equals(castOther.getPlanoContaNome())))
				&& ((this.getIdFormaPagamento() == castOther.getIdFormaPagamento())
						|| (this.getIdFormaPagamento() != null && castOther.getIdFormaPagamento() != null
								&& this.getIdFormaPagamento().equals(castOther.getIdFormaPagamento())))
				&& ((this.getCodigo() == castOther.getCodigo()) || (this.getCodigo() != null
						&& castOther.getCodigo() != null && this.getCodigo().equals(castOther.getCodigo())))
				&& ((this.getIdTransacao() == castOther.getIdTransacao())
						|| (this.getIdTransacao() != null && castOther.getIdTransacao() != null
								&& this.getIdTransacao().equals(castOther.getIdTransacao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getData() == null ? 0 : this.getData().hashCode());
		result = 37 * result + (getNumero() == null ? 0 : this.getNumero().hashCode());
		result = 37 * result + (getValor() == null ? 0 : this.getValor().hashCode());
		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result + (getVencimento() == null ? 0 : this.getVencimento().hashCode());
		result = 37 * result + (getDataBaixa() == null ? 0 : this.getDataBaixa().hashCode());
		result = 37 * result + (getValorBaixa() == null ? 0 : this.getValorBaixa().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getIdPessoa() == null ? 0 : this.getIdPessoa().hashCode());
		result = 37 * result + (getPessoaNome() == null ? 0 : this.getPessoaNome().hashCode());
		result = 37 * result + (getIdCentroCusto() == null ? 0 : this.getIdCentroCusto().hashCode());
		result = 37 * result + (getCentroCustoNome() == null ? 0 : this.getCentroCustoNome().hashCode());
		result = 37 * result + (getIdPlanoConta() == null ? 0 : this.getIdPlanoConta().hashCode());
		result = 37 * result + (getPlanoContaNome() == null ? 0 : this.getPlanoContaNome().hashCode());
		result = 37 * result + (getIdFormaPagamento() == null ? 0 : this.getIdFormaPagamento().hashCode());
		result = 37 * result + (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result + (getIdTransacao() == null ? 0 : this.getIdTransacao().hashCode());
		return result;
	}

}
